name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liqT8pcu9m1cBl46"
GITHUB_OWNER = "Mrstones188"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "http://navsphere-4c5.pages.dev/"
NEXT_PUBLIC_API_URL="http://navsphere-4c5.pages.dev/"

